apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: ibm-etcd-operator
    app.kubernetes.io/managed-by: ibm-etcd-operator
    app.kubernetes.io/name: ibm-etcd-operator
  name: etcdbackups.etcd.database.coreos.com
spec:
  group: etcd.database.coreos.com
  names:
    kind: EtcdBackup
    listKind: EtcdBackupList
    plural: etcdbackups
    singular: etcdbackup
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
      type: object
  version: v1beta3
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
