---
- name: Check if generated credentials secret exists
  k8s_info:
    api_version: v1
    kind: Secret
    name: '{{ etcd_cluster_name }}-auth'
    namespace: '{{ etcd_namespace }}'
  register: cred_existing_status
  ignore_errors: true

- name: Create credentials secret
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: '{{ etcd_cluster_name }}-auth'
        namespace: '{{ etcd_namespace }}'
        labels:
          app: "{{ etcd_app_label }}"
          etcd_cluster: "{{ etcd_cluster_name }}"
      data:
        password: "{{ lookup('password',
                 '/dev/null chars=ascii_lowercase,hexdigits length=20')
                 | b64encode }}"
  when: cred_existing_status.resources | length == 0

- name: Set auth secret name to be used by Etcd
  set_fact:
    auth_secret_name_to_bound: '{{ etcd_cluster_name }}-auth'