---
- name: set etcd_cluster_phase
  set_fact:
    etcd_cluster_phase: "existing"
  when: etcd_stateful_set|length > 0

- block:

  - name: set the "{{ etcd_cluster_name }}" resources state=present
    k8s:
      state: "present"
      definition: "{{ lookup('template', 'ss.yaml.j2') | from_yaml }}"

  - name: set tls status facts when present
    set_fact:
      peer_tls_secret: "{{ _tls.static.member.peer_secret }}"
      server_tls_secret: "{{ _tls.static.member.server_secret }}"
      operator_tls_secret: "{{ _tls.static.operator_secret }}"
    when: etcd_secure_client == "present" and etcd_secure_peer == "present"

  - name: set tls status facts when absent
    set_fact:
      peer_tls_secret: ""
      server_tls_secret: ""
      operator_tls_secret: ""
    when: etcd_secure_client == "absent" and etcd_secure_peer == "absent"

  - name: set cluster status when new
    vars:
      etcd_status: "Creating"
      peer_tls_secret: "{{ peer_tls_secret }}"
      server_tls_secret: "{{ server_tls_secret }}"
      operator_tls_secret: "{{ operator_tls_secret }}"
    k8s_status:
      api_version: etcd.database.coreos.com/v1beta3
      kind: EtcdCluster
      name: "{{ etcd_cluster_name }}"
      namespace: "{{ etcd_namespace }}"
      status: "{{ lookup('template', 'status.yaml') | from_yaml }}"

  when: etcd_cluster_phase == "new"

- name: set TLS status variables when present
  set_fact:
    peer_tls_secret: "{{ _etcd_database_coreos_com_etcdcluster.get('status', {}).get('peerTLSSecret', '') }}"
    server_tls_secret: "{{ _etcd_database_coreos_com_etcdcluster.get('status', {}).get('serverTLSSecret', '') }}"
    operator_tls_secret: "{{ _etcd_database_coreos_com_etcdcluster.get('status', {}).get('operatorTLSSecret', '') }}"
  when: etcd_cluster_phase == "existing" and etcd_secure_client == "present" and etcd_secure_peer == "present"

- name: set TLS status variables when absent
  set_fact:
    peer_tls_secret: ""
    server_tls_secret: ""
    operator_tls_secret: ""
  when: etcd_cluster_phase == "existing" and etcd_secure_client == "absent" and etcd_secure_peer == "absent"

- block:

  - name: set cluster member names
    set_fact:
      etcd_cluster_member_names: "{{ etcd_cluster_member_names + [etcd_cluster_name + '-' + item|string] }}"
    with_sequence: start={{0}} end={{size|int - 1 if size|int>0 else 1}}
    when: etcd_cluster_phase == "existing"
  when: size| int > 0

- name: check if TLS rotation
  include_tasks: rotate_tls.yaml
  when: etcd_cluster_phase == "existing" and (etcd_secure_client == "present" or etcd_secure_peer == "present")

- name: get members of cluster
  vars:
    members: "{{q('etcd_member',cluster_host=etcd_cluster_name+'-client.'+etcd_namespace+'.svc',cluster_port=etcd_client_port)}}"
  set_fact:
    etcd_cluster_members: "{{ members }}"
  when: (etcd_cluster_phase == "existing" and etcd_secure_client == "absent")
  ignore_errors: yes

- name: get members of cluster when secure client
  vars:
    members: "{{ q('etcd_member', cluster_host= etcd_cluster_name + '-client.' + etcd_namespace + '.svc',
                  cluster_port=etcd_client_port,
                  ca_cert=tls_directory + '/etcd-ca.crt',
                  cert_cert=tls_directory + '/etcd-client.crt',
                  cert_key=tls_directory + '/etcd-client.key') }}"
  set_fact:
    etcd_cluster_members: "{{ members }}"
  when: (etcd_cluster_phase == "existing" and etcd_secure_client == "present")
  ignore_errors: yes

- name: update tls variables
  set_fact:
    peer_tls_secret: "{{ _tls.static.member.peer_secret }}"
    server_tls_secret: "{{ _tls.static.member.server_secret }}"
    operator_tls_secret: "{{ _tls.static.operator_secret }}"
  when: etcd_cluster_phase == "existing" and etcd_secure_client == "present" and etcd_secure_peer == "present"

- block:

  - name: Set status and exit when cluster is unavailable
    vars:
      etcd_status: "Unavailable"
      etcd_status_reason: "Etcd is trying to establish quorum"
      peer_tls_secret: "{{ peer_tls_secret }}"
      server_tls_secret: "{{ server_tls_secret }}"
      operator_tls_secret: "{{ operator_tls_secret }}"
    k8s_status:
      api_version: etcd.database.coreos.com/v1beta3
      kind: EtcdCluster
      name: "{{ etcd_cluster_name }}"
      namespace: "{{ etcd_namespace }}"
      status: "{{ lookup('template', 'status.yaml') | from_yaml }}"

  - fail:
      msg: cluster is unavailable

  when: etcd_cluster_phase == "existing" and 0 < etcd_cluster_members|length <= (etcd_stateful_set[0].spec.replicas/2)

- name: Set status when cluster is available
  vars:
    etcd_status: Available
    peer_tls_secret: "{{ peer_tls_secret }}"
    server_tls_secret: "{{ server_tls_secret }}"
    operator_tls_secret: "{{ operator_tls_secret }}"
  k8s_status:
    api_version: etcd.database.coreos.com/v1beta3
    kind: EtcdCluster
    name: "{{ etcd_cluster_name }}"
    namespace: "{{ etcd_namespace }}"
    status: "{{ lookup('template', 'status.yaml') | from_yaml }}"
  when: etcd_cluster_phase == "existing" and
        ((etcd_cluster_members|length > (size/2 + 1)) or
        (etcd_cluster_members|length <= 2 and etcd_cluster_members|length == size))

- name: get members of cluster when secure client
  vars:
    members: "{{ q('etcd_member', cluster_host= etcd_cluster_name + '-client.' + etcd_namespace + '.svc',
                  cluster_port=etcd_client_port,
                  ca_cert=tls_directory + '/etcd-ca.crt',
                  cert_cert=tls_directory + '/etcd-client.crt',
                  cert_key=tls_directory + '/etcd-client.key') }}"
  set_fact:
    etcd_cluster_members: "{{ members }}"
  when: (etcd_cluster_phase == "existing" and etcd_secure_client == "present")
  ignore_errors: yes

- block:

  - name: Change initial_size if Scaling
    set_fact:
      initial_size: "{{ etcd_stateful_set[0].spec.replicas if (etcd_stateful_set[0].spec.replicas != 0) else size }}"

  - name: Set status when Scaling
    vars:
      etcd_status: Scaling
      peer_tls_secret: "{{ peer_tls_secret }}"
      server_tls_secret: "{{ server_tls_secret }}"
      operator_tls_secret: "{{ operator_tls_secret }}"
    k8s_status:
      api_version: etcd.database.coreos.com/v1beta3
      kind: EtcdCluster
      name: "{{ etcd_cluster_name }}"
      namespace: "{{ etcd_namespace }}"
      status: "{{ lookup('template', 'status.yaml') | from_yaml }}"

  - name: set new size
    set_fact:
      new_etcd_stateful_set: "{{ lookup('template', 'ss.yaml.j2') | from_yaml }}"
      scaling: true
    when: etcd_cluster_phase == "existing"

  - name: patch the "{{ etcd_cluster_name }}" resources
    k8s:
      state: "present"
      definition: "{{ new_etcd_stateful_set }}"
    when: etcd_cluster_phase == "existing"

  when: size != etcd_stateful_set[0].spec.replicas

- block:

  - name: get ids of members to be removed
    vars:
      etcd_remove_members: "{{ (etcd_cluster_members | sort(attribute='name'))[size:] }}"
    include_tasks: remove_members.yaml
    loop: "{{ etcd_remove_members | reverse | list}} "

  when: etcd_cluster_phase == "existing" and (etcd_cluster_members|length|int) > size

- name: make sure all the pods are running
  k8s_info:
    kind: StatefulSet
    api_version: apps/v1
    namespace: "{{ etcd_namespace }}"
    name: "{{ etcd_cluster_name }}"
  register: sts
  until: sts.get("resources", []) and sts.resources[0].get("status", {}).get("readyReplicas", 0) == size
  retries: 30
  delay: 10

- name:  Get Cluster availablity
  set_fact:
    cluster_availablity: "{{ ((sts.resources[0].status.readyReplicas) | int)>=(size+1)/2 }}"
  when: (execute_enable_authentication and authentication=="NotEnabled")

- name: Enable authentication 
  set_fact:
    authentication_enabled: "{{q('etcd_auth',cluster_host=etcd_cluster_name+'-client.'+etcd_namespace+'.svc',cluster_port=etcd_client_port, username=auth_username, password=auth_password )}}"
  when: (cluster_availablity is defined and cluster_availablity and execute_enable_authentication and authentication=="NotEnabled" and etcd_secure_client == "absent")

- name:  Enable authentication when secure client
  set_fact:
    authentication_enabled: "{{q('etcd_auth',cluster_host=etcd_cluster_name+'-client.'+etcd_namespace+'.svc',
                  cluster_port=etcd_client_port, 
                  username=auth_username, password=auth_password,
                  ca_cert=tls_directory + '/etcd-ca.crt',
                  cert_cert=tls_directory + '/etcd-client.crt',
                  cert_key=tls_directory + '/etcd-client.key' )}}"
  when: (cluster_availablity is defined and cluster_availablity and execute_enable_authentication and authentication=="NotEnabled" and etcd_secure_client == "present")

- name: Change authentication status
  set_fact:
    authentication: "Enabled"
  when: (authentication_enabled is defined and authentication_enabled and execute_enable_authentication and authentication=="NotEnabled")

- name: Set status as authentication enabled
  k8s_status:
    api_version: etcd.database.coreos.com/v1beta3
    kind: EtcdCluster
    name: "{{ etcd_cluster_name }}"
    namespace: "{{ etcd_namespace }}"
    status: "{{ lookup('template', 'status.yaml') | from_yaml }}"
  when: (authentication_enabled is defined and authentication_enabled and execute_enable_authentication)

- name: set fact for initial cluster size
  set_fact:
    initial_size: "{{ size }}"

- name: make new size the initial size
  k8s:
    state: "present"
    definition: "{{ lookup('template', 'ss.yaml.j2') | from_yaml }}"
  when: scaling is defined
