apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: etcd-ha-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Operator for Etcd
  displayName: etcd-ha-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - operator
  - etcd
  - keyvalue store
  links:
  - name: Etcd Operator
    url: ''
  maintainers:
  - email: harinarayananmohan@gmail.com
    name: HarinarayananMohan
  maturity: alpha
  provider:
    name: Openshift
  version: 0.0.0
