---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: etcd-ha-operator-role
  labels:
    app.kubernetes.io/instance: etcd-ha-operator
    app.kubernetes.io/managed-by: etcd-ha-operator
    app.kubernetes.io/name: etcd-ha-operator
rules:
- apiGroups:
  - etcd.database.coreos.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - replicasets
  verbs:
  - "*"
- apiGroups: ["apps"]
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  -  security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - restricted
- apiGroups:
    - networking.k8s.io
  resources:
    - networkpolicies
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
# +kubebuilder:scaffold:rules
